site_name: SURF Documentation
theme: 
  name: readthedocs
  color_mode: auto
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage: usage.md
  - API Reference:
    - Overview: api/overview.md
    - UTILS: api/utils.md
    - POWER LAW TOOLS: api/power_law_tools.md
    - PLOTTING: api/plotting.md
    - PLANE FITTING: api/ransac3d.md
plugins:
  - mkdocstrings


