site_name: SURF Documentation
theme: 
  name: readthedocs
  color_mode: auto
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - PLOTTING-API: api/plotting.md
# plugins:
  # - mkdocstrings
