site_name: SURF Documentation

repo_url: https://code.usgs.gov/talongi/surf

theme: 
  name: material
  palette:
    # scheme: slate
    # primary: gray
    # accent: gray
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: gray
      accent: gray
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: gray
      accent: gray
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Arial
    code: Fira Code
  icon:
    logo: material/format-strikethrough-variant
    repo: fontawesome/brands/gitlab



nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage (examples): usage.md
  - API Reference:
    - UTILS: api/utils.md
    - POWER LAW TOOLS: api/power_law_tools.md
    - PLOTTING: api/plotting.md
    - PLANE FITTING: api/ransac3d.md

plugins:
  - mkdocstrings
  - search


